version: '3.4'

services:
  proxy:
    build:
      context: proxy
    container_name: misp_proxy
    restart: unless-stopped
    image: misp-proxy:latest
    ports:
      - 80:80
      - 443:443

  web:
    build: web
    container_name: misp_web
    image: misp:latest
    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
      - misp-docker-web:/var/www/MISP
    env_file:
      - ".env"

  db:
    container_name: misp_db
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    volumes:
      - misp-docker-db:/var/lib/mysql
    env_file:
      - ".env"
volumes:
  misp-docker-db:
    name: "misp-docker-db"
  misp-docker-web:
    name: "misp-docker-web"
