# This is a basic workflow to help you get started with Actions

name: MISP-DOCKER

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env file
        run: cp template.env .env
      - name: Build the stack
        run: docker-compose up
